import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {normalizeJob} from './dist/core.js';
const ROOT=path.resolve(fileURLToPath(new URL('./dist/',import.meta.url)));
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.txt':'text/plain; charset=utf-8','.json':'application/json'};
const csp="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'";
export function feedURL(provider,board){if(!/^[A-Za-z0-9_-]{1,100}$/.test(board))throw Error('Invalid employer board token.');if(provider==='Greenhouse')return `https://boards-api.greenhouse.io/v1/boards/${board}/jobs?content=true`;if(provider==='Lever')return `https://api.lever.co/v0/postings/${board}?mode=json`;throw Error('Unsupported provider.');}
function plain(s){return String(s||'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();}
export function feedJobs(provider,data,company){const rows=provider==='Greenhouse'?data.jobs:data;if(!Array.isArray(rows))throw Error('The employer feed returned an unexpected format.');return rows.slice(0,500).map(j=>({title:provider==='Greenhouse'?j.title:j.text,company,location:provider==='Greenhouse'?j.location?.name:j.categories?.location,mode:/remote/i.test(JSON.stringify([j.location,j.categories?.location,j.workplaceType]))?'Remote':/hybrid/i.test(JSON.stringify([j.location,j.categories?.location,j.workplaceType]))?'Hybrid':'On-site',remoteEligibility:'Unknown',url:provider==='Greenhouse'?j.absolute_url:j.hostedUrl,description:plain(provider==='Greenhouse'?j.content:[j.descriptionPlain,...(j.lists||[]).map(l=>`${l.text}: ${l.content}`),j.additionalPlain].join('\n')),source:provider,postedAt:provider==='Lever'&&j.createdAt?new Date(j.createdAt).toISOString():''})).filter(j=>j.title&&j.description);}
async function boundedJSON(response,limit=5*1024*1024){if(!response.ok)throw Error(`Provider returned HTTP ${response.status}.`);let size=0;const chunks=[];for await(const chunk of response.body){size+=chunk.length;if(size>limit)throw Error('Provider response exceeds the size limit.');chunks.push(chunk);}return JSON.parse(Buffer.concat(chunks).toString('utf8'));}
export function createServer(){let busy=false,lastMake=0;return http.createServer(async(req,res)=>{const send=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data));};
 try{const host=req.headers.host,port=req.socket.localPort;if(![`127.0.0.1:${port}`,`localhost:${port}`].includes(host)){send(403,{error:'Invalid host.'});return;}const url=new URL(req.url,`http://${host}`);
 if(url.pathname.startsWith('/api/')){if(req.method!=='POST'){send(405,{error:'Use POST.'});return;}if(req.headers.origin!==`http://${host}`||!req.headers['content-type']?.startsWith('application/json')){send(403,{error:'Only same-origin application requests are accepted.'});return;}let body='';for await(const c of req){body+=c;if(Buffer.byteLength(body)>150000){send(413,{error:'Request too large.'});return;}}const input=JSON.parse(body||'{}');
 if(url.pathname==='/api/generate'){if(!process.env.OLLAMA_MODEL){send(503,{error:'Set OLLAMA_MODEL to an installed local model, start Ollama, and restart this local server. No paid fallback is enabled.'});return;}if(typeof input.prompt!=='string'||input.prompt.length<20){send(400,{error:'A generation prompt is required.'});return;}if(busy){send(429,{error:'A local generation is already running.'});return;}busy=true;try{const response=await fetch('http://127.0.0.1:11434/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OLLAMA_MODEL,prompt:input.prompt,stream:false}),signal:AbortSignal.timeout(180000),redirect:'error'});const out=await boundedJSON(response,200000);if(typeof out.response!=='string')throw Error('Local model did not return text.');send(200,{text:out.response});}finally{busy=false;}return;}
 if(url.pathname==='/api/feed'){if(typeof input.company!=='string'||!input.company.trim())throw Error('Employer name required.');const response=await fetch(feedURL(input.provider,input.board),{signal:AbortSignal.timeout(25000),redirect:'error'});send(200,{jobs:feedJobs(input.provider,await boundedJSON(response),input.company)});return;}
 if(url.pathname==='/api/make'){if(!process.env.MAKE_WEBHOOK_URL){send(503,{error:'Configure a private MAKE_WEBHOOK_URL in the local environment. Never paste a secret webhook URL into the public app.'});return;}const target=new URL(process.env.MAKE_WEBHOOK_URL);if(target.protocol!=='https:'||!/^hook\.[a-z0-9-]+\.make\.com$/.test(target.hostname)||target.username||target.password)throw Error('The configured webhook must be an official regional HTTPS Make hook.');if(Date.now()-lastMake<60000){send(429,{error:'Wait one minute before running Make intake again.'});return;}let suppliedJobs=[];if(input.jobs!==undefined){if(!Array.isArray(input.jobs)||input.jobs.length>20)throw Error('Send up to 20 jobs in a batch.');suppliedJobs=input.jobs.map(raw=>{const j=normalizeJob(raw);if(!j.url)throw Error('A real source URL is required.');return {title:j.title,company:j.company,url:j.url,description:j.description,location:j.location,mode:j.mode,remoteEligibility:j.remoteEligibility,postedAt:j.postedAt,source:j.source};});}lastMake=Date.now();const response=await fetch(target,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:suppliedJobs.length?'normalize_jobs':'collect_jobs',requestId:randomUUID(),jobs:suppliedJobs}),signal:AbortSignal.timeout(40000),redirect:'error'});const output=await boundedJSON(response);send(200,output);return;}
 send(404,{error:'Unknown adapter.'});return;}
 if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);res.end();return;}const decoded=decodeURIComponent(url.pathname),file=path.resolve(ROOT,'.'+(decoded==='/'?'/index.html':decoded));if(!file.startsWith(ROOT+path.sep)&&file!==ROOT){res.writeHead(403);res.end();return;}const bytes=await readFile(file);res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream','Content-Security-Policy':csp,'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','Cache-Control':'no-cache'});res.end(req.method==='HEAD'?undefined:bytes);
 }catch(err){if(err.code==='ENOENT'){res.writeHead(404);res.end('Not found');}else send(400,{error:err.name==='TimeoutError'?'Provider timed out. No automatic retry was sent.':err.message==='fetch failed'?'Provider unavailable. Check your local service or network connection.':String(err.message).replace(/https?:\/\/\S+/g,'[provider URL]')});}});}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const port=Number(process.env.PORT||4173);createServer().listen(port,'127.0.0.1',()=>console.log(`Applydesk running at http://127.0.0.1:${port}`));}
